### ISSUE TITLE
Idea for accelerate your project

### ISSUE THREAD

**Issue by gauthierc** [makkes/gitlab-cli#2]
Thanks for your application
Do you know this project https://github.com/xanzy/go-gitlab ?
And this other https://github.com/plouc/go-gitlab-client ?
I think that the first is a good base for your application.

**Comment by makkes** [comment]
Thanks for your input, @gauthierc. I'll see if it would make sense to merge my efforts into one those projects or make use of a Go library. Currently, I'm trying to keep external dependencies to a minimum. Thanks!
