### ISSUE TITLE
Add explanation of possible flags to 'var create'

### ISSUE THREAD

**Issue by erikthered** [makkes/gitlab-cli#20]
The help for `var create` doesn't explain possible values for flags and I couldn't really tell from the source what valid values look like.

**Comment by makkes** [comment]
Thanks, @erikthered for your feedback. The flags for every command are listed at the very bottom of the help output, e.g. here:
```sh
$ gitlab-cli help pipelines
List pipelines of a project

Usage:
  gitlab-cli pipelines PROJECT [flags]

Flags:
  -a, --all      Show all pipelines (default shows just running/pending.)
  -h, --help     help for pipelines
  -q, --quiet    Only display numeric IDs
  -r, --recent   Show only the most recent pipeline
```
For `var create` there's only the `--help` flag.

Regarding valid values I'll add some documentation to the help ouput of `var create`.

**Comment by erikthered** [comment]
Ah yeah I misunderstood, I thought flags in that case was referring to things like masked, protected, environment in the context of variables.
