### ISSUE TITLE
Add pagination support

### ISSUE THREAD

**Issue by erikthered** [makkes/gitlab-cli#21]
Not sure if this is due to inherent pagination in the GitLab API but for a project with over 20 CI/CD vars, only the first 20 are listed.

**Comment by makkes** [comment]
Thanks for the feedback! Yep, `gitlab-cli` isn't paging at all. I'll have to think about how to implement it (prompt for more pages, add a flag to get all pages, get all pages by default, ...).

**Comment by erikthered** [comment]
I'm going to change the title of this issue to better fit the desired enhancement.

**Comment by makkes** [comment]
The GitLab API has a pretty simple way of paginating results: https://docs.gitlab.com/ee/api/#pagination

We could add a `--page` parameter to the CLI in order to let users choose which page to fetch. The `X-Total-Pages` header could be used to somehow display that more data is available.

**Comment by erikthered** [comment]
That sounds like a reasonable approach, I should have some time today to
try to work on this.

**Comment by erikthered** [comment]
Closed by #29
