### ISSUE TITLE
Remove -cli from the executable name?

### ISSUE THREAD

**Issue by bfontaine** [makkes/gitlab-cli#25]
Hello, any reason to append `-cli` to the executable name? We know it’s a CLI tool, since we use it… from the CLI. Typing `$ gitlab projects` would seem more natural than `$ gitlab-cli projects`.

Thoughts?

**Comment by makkes** [comment]
Sounds reasonable. Do you want to create a PR for that?

**Comment by bfontaine** [comment]
Yep I can do that

**Comment by makkes** [comment]
Awesome. Thanks!
