### ISSUE TITLE
question(scopes): required scopes

### ISSUE THREAD

**Issue by Kristinita** [makkes/gitlab-cli#3]
### 1. Summary

I can't find, which scopes I need to select for gitlab-cli log in.

### 2. Details

[**Documentation**](https://github.com/makkes/gitlab-cli#installation-and-usage):

> All commands of gitlab-cli currently require that you are authenticated. To do so you issue `gitlab-cli login YOUR_TOKEN`. You obtain a personal access token at **<https://gitlab.com/profile/personal_access_tokens>**.

No information about scopes, that users needs to select:

![GitLab scopes](https://i.imgur.com/AJR79Zo.png)

Thanks.

**Comment by makkes** [comment]
Thanks @Kristinita for raising this. I have extended the README.
