### ISSUE TITLE
Possible to access repos on a self-hosted Gitlab?

### ISSUE THREAD

**Issue by asitemade4u** [makkes/gitlab-cli#35]
I am trying to access our self-hosted Gitlab server but cannot find the settings applicable in the `.gitlab-cli.json` file.
Is that even possible?

**Comment by makkes** [comment]
Hi @asitemade4u, even though I haven't tested it you should be able to. Please have a look at `gitlab login -h`. The `login` command accepts a URL that you can provide.

**Comment by asitemade4u** [comment]
Thanks for the answer.
I tried and here is the error message I got  [I obfuscate the details]:

`
gitlab login <thetoken> <thehostname>
WARNING: Error reading configuration: unexpected end of JSON input
Error: Cannot login to lab.<thehostname>: Get <thehostname>/api/v4/user: unsupported protocol scheme ""
`
I am using the latest version of GitLab.

**Comment by makkes** [comment]
Oh, that should be an easy one. Try:
```
gitlab login <thetoken> https://<thehostname>
```
I didn't get to adding the scheme if it's missing.

**Comment by asitemade4u** [comment]
Nope, still not working [I replaced https by http as it is a purely 
local server}.

**Comment by asitemade4u** [comment]
The message here is: unexpected end of JSON input

**Comment by asitemade4u** [comment]
FOUND IT!

  * I am hosting my Gitlab server within a docker container
  * the *hostname* of the container was the parameter I passed to gitlab-cli
  * now that I passed the *IP ADDRESS* of the container, it works!

Maybe you could consider allowing the hostname though...

**Comment by makkes** [comment]
There's nothing in the code prohibiting using a docker container's host name as long as it's resolvable using the host system's DNS.

**Comment by asitemade4u** [comment]
You are right again. I just tried it anew and it worked!
