### ISSUE TITLE
animated gif uses wrong command name?

### ISSUE THREAD

**Issue by oddhack** [makkes/gitlab-cli#44]
I just downloaded onto Debian using the curl method and found that the 'gitlab-cli' example in the animated gif on the repo doesn't work because the command is called 'gitlab' now :-)

**Comment by makkes** [comment]
Thanks for raising this, I was wondering when someone would notice. I haven't had the time to re-do this, yet. Will prioritize it now.

**Comment by makkes** [comment]
Since creating an animated GIF that (1) doesn't exceed 1 MiB file size and (2) is readable at around 700px width turns out to be not as easy as I want it to be I just recorded and uploaded an asciinema video in 49830177fb89dbc5568272e5e95a721d984fd283.

**Comment by oddhack** [comment]
Oh, cool! I had no idea asciinema was a thing.
