### ISSUE TITLE
Add completion for zsh

### ISSUE THREAD

**Issue by ShivamJoker** [makkes/gitlab-cli#73]
Hey can you please add completion for zsh as well ?

**Comment by makkes** [comment]
Thanks @ShivamJoker, I just added zsh completion. As this is a breaking change, it won't enter the 3.x release, though. I'll cut another 4.0.0 beta today, though.

**Comment by makkes** [comment]
Released [4.0.0 RC 1](https://github.com/makkes/gitlab-cli/releases/tag/v4.0.0-rc.1). If you'd like to update, run:

```sh
gitlab update --pre --major
```
